### ISSUE TITLE
Volledigheid van de stylesheet

### ISSUE THREAD

**Issue by senneb31** [DivaniNL/look-and-feel-styleguide#21]
In de buttons komt formulier elementen eerder dan buttons. Maar in de indeling komt buttons eerder dan formulier elementen. Misschien de buttons formulier elementen en buttons omdraaien zodat het op volgorde staat.

**Comment by DivaniNL** [comment]
De volgorde in de navigatie is aangepast.
[https://github.com/DivaniNL/look-and-feel-styleguide/commit/7a0d5c8de55cbbba6da9562919fbf2954dab3f6f](https://github.com/DivaniNL/look-and-feel-styleguide/commit/7a0d5c8de55cbbba6da9562919fbf2954dab3f6f
)

Is dit wat jullie bedoelden?

**Comment by senneb31** [comment]
Ja:)
