### ISSUE TITLE
Custom properties op juiste element

### ISSUE THREAD

**Issue by senneb31** [DivaniNL/look-and-feel-styleguide#22]
:root is niet te vinden, properties staan wel op de juiste plaats

**Comment by Karima002** [comment]
De properties kunnen beter staan in de` body {`. Dit werd op de woensdag uitgelegd door Joost. 
![WhatsApp Image 2024-11-15 at 11 06 51](https://github.com/user-attachments/assets/e883534d-1431-468f-b19b-5841e552416c)

**Comment by DivaniNL** [comment]
Dit is afkomstig uit de workshop: Workshop stylesheets for styleguides op 13 November 2024
